<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use app\services\UrlService;
use http\Url;
use yii\web\AssetBundle;

/**
 * Main application asset bundle.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';

    public function registerAssetFiles($view)
    {
        //加一个版本号， 目的： 使浏览器获取最新的css/js文件
        $release = '20180918';
        $this->css = [
            UrlService::buildUrl('/bootstrap/css/bootstrap.min.css', ['v' => $release]),
            UrlService::buildUrl('/css/app.css'),
            UrlService::buildUrl('/css/base.css')
        ];
        $this->js = [
            UrlService::buildUrl('/js/jquery.min.js'),
            UrlService::buildUrl('bootstrap/js/bootstrap.min.js')
        ];
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}
